# Generated by Django 3.2.7 on 2022-03-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0002_rename_name_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='Vector (3).png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
