# Generated by Django 3.2.7 on 2022-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_alter_project_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
